name: Feature request
description: Suggest an idea for this project
labels: "Status: Needs triage :mag:, Issue: Feature Request :nerd_face:"

body:
  - type: markdown
    attributes:
      value: >-
        Hi there! Thank you so much for taking the time to fill in this feature request form.
        It will be a valuable contribution to ActSys.

        We'd appreciate it if you could search on ActSys's existing issues prior to filing
        a feature request to avoid any duplicate tickets, as we have limited maintainer capacity to triage
        them. Thanks!
  - type: dropdown
    attributes:
      label: Which package?
      options:
        - actuarial-ui
        - actuarial-core
        - actuarial-ai
        - actuarial-ml
  - type: textarea
    attributes:
      label: What's the problem this feature will solve?
      description: >-
        What are you trying to do, that you are unable to achieve with ActSys as it
        currently stands?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: >-
        Clear and concise description of what you want to happen. Please use examples
        of real world use cases that this would help with, and how it solves the
        problem described above.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternative Solutions
      description: >-
        Have you tried to workaround the problem using ActSys or other tools? Or a
        different approach to solving this issue? Please elaborate here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: >-
        Add any other context, links, etc. relevant to the feature request.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Code of Conduct
      options:
        - label: >-
            I agree to follow the  [Code of Conduct](https://github.com/jeffamaxey/actsys/blob/main/CODE_OF_CONDUCT.md).
          required: true
